import { AppContextProvider } from '@/hooks/useGlobalContext'
import Image from 'next/image'
import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <AppContextProvider>
        <body>
          <nav className="py-5 mb-4 flex justify-center">
            <Link href="/">
              <Image src="/dfns.png" alt="" width={50} height={50}></Image>
            </Link>
          </nav>
          <div className="prose mx-auto">
            {children}

            <div className="mt-10">
              <Link href="/" className="btn no-underline">
                ← Back to main page
              </Link>
            </div>
          </div>
        </body>
      </AppContextProvider>
    </html>
  )
}
