name: publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: npm-publish
      deployment: false
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: '0'

      - name: install node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: install packages
        run: |
          npm config set ignore-scripts true
          npm ci --prefer-offline --no-audit --cache .npm

      - name: compile packages
        run: npm run cb:all

      - name: publish packages
        run: |
          packages=(
            "@dfns/lib-algorand"
            "@dfns/lib-aptos"
            "@dfns/lib-bitcoinjs"
            "@dfns/lib-concordium"
            "@dfns/lib-cosmjs"
            "@dfns/lib-ethersjs5"
            "@dfns/lib-ethersjs6"
            "@dfns/lib-hedera"
            "@dfns/lib-iota"
            "@dfns/lib-kaspa"
            "@dfns/lib-meshsdk"
            "@dfns/lib-near"
            "@dfns/lib-polkadot"
            "@dfns/lib-polymesh"
            "@dfns/lib-solana"
            "@dfns/lib-stellar"
            "@dfns/lib-sui"
            "@dfns/lib-taquito"
            "@dfns/lib-ton"
            "@dfns/lib-tron"
            "@dfns/lib-vechain"
            "@dfns/lib-viem"
            "@dfns/lib-xrpl"
            "@dfns/sdk"
            "@dfns/sdk-awskmssigner"
            "@dfns/sdk-browser"
            "@dfns/sdk-keyexport-utils-nodejs"
            "@dfns/sdk-keyexport-utils-bundler"
            "@dfns/sdk-keyimport-utils-nodejs"
            "@dfns/sdk-keyimport-utils-bundler"
            "@dfns/sdk-keysigner"
            "@dfns/sdk-react-native"
          )

          for packageName in "${packages[@]}"; do
            cd dist/"${packageName}"
            echo "Publishing ${packageName}..."
            npm publish --workspaces=false
            cd - >/dev/null
          done

