name: semantic-release

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment:
      name: npm-publish
      deployment: false
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 1
          persist-credentials: false

      - uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: app-token
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PK }}

      - name: Semantic release
        id: semantic_release
        uses: cycjimmy/semantic-release-action@b12c8f6015dc215fe37bc154d4ad456dd3833c90 # v6.0.0
        with:
          extra_plugins: |
            @semantic-release/exec
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Trigger publish workflow
        if: steps.semantic_release.outputs.new_release_published == 'true'
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: gh workflow run publish.yaml
