name: semantic-release

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment:
      name: npm-publish
      deployment: false
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1
          persist-credentials: false

      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PK }}

      - name: Semantic release
        id: semantic_release
        uses: cycjimmy/semantic-release-action@b12c8f6015dc215fe37bc154d4ad456dd3833c90 # v6.0.0
        with:
          extra_plugins: |
            @semantic-release/exec
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Trigger publish workflow
        if: steps.semantic_release.outputs.new_release_published == 'true'
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: gh workflow run publish.yaml
